import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from "framer-motion";
import { useFeedback } from "@/context/use-feedback";
export function Mascot() {
    const { open, isThanking } = useFeedback();
    return (_jsxs(motion.div, { onClick: open, className: "absolute -right-8 -bottom-8 z-20 cursor-pointer", whileHover: { scale: 1.1, rotate: 2 }, whileTap: { scale: 0.95 }, animate: isThanking
            ? { rotate: [0, 20, -20, 15, -15, 0] }
            : { y: [0, -6, 0] }, transition: isThanking
            ? { duration: 0.8 }
            : { duration: 3, repeat: Infinity }, children: [_jsx("div", { className: "\r\n          absolute inset-0 -z-10\r\n          rounded-2xl\r\n          bg-gradient-to-br\r\n          from-indigo-500\r\n          via-fuchsia-500\r\n          to-cyan-400\r\n          blur-xl\r\n          opacity-70\r\n        " }), _jsx("div", { className: "\r\n          relative\r\n          rounded-2xl\r\n          bg-white/90\r\n          backdrop-blur-xl\r\n          border border-white/30\r\n          shadow-2xl\r\n          p-4\r\n        ", children: _jsxs("svg", { width: "44", height: "44", viewBox: "0 0 100 100", children: [_jsx("circle", { cx: "50", cy: "50", r: "45", fill: "#ffffff" }), _jsx("circle", { cx: "35", cy: "45", r: "5", fill: "#111827" }), _jsx("circle", { cx: "65", cy: "45", r: "5", fill: "#111827" }), _jsx("path", { d: "M35 60 Q50 72 65 60", stroke: "#111827", strokeWidth: "4", fill: "none", strokeLinecap: "round" })] }) }), _jsx(AnimatePresence, { children: isThanking && (_jsx(motion.div, { initial: { opacity: 0.7, scale: 1 }, animate: { opacity: 0, scale: 2.5 }, exit: { opacity: 0 }, transition: { duration: 0.8 }, className: "\r\n              absolute inset-0\r\n              rounded-2xl\r\n              bg-fuchsia-500/40\r\n              blur-xl\r\n              -z-20\r\n            " })) }), _jsx(AnimatePresence, { children: isThanking && (_jsxs(motion.div, { initial: { opacity: 0, y: 20, scale: 0.95 }, animate: { opacity: 1, y: -20, scale: 1 }, exit: { opacity: 0, y: 10 }, transition: { duration: 0.3 }, className: "\r\n              absolute -top-32 right-0\r\n              w-48\r\n              rounded-2xl\r\n              bg-white/95\r\n              backdrop-blur-2xl\r\n              border border-white/30\r\n              shadow-2xl\r\n              p-4\r\n              text-center\r\n            ", children: [_jsx("p", { className: "text-sm font-semibold text-zinc-900", children: "Thank you \uD83D\uDC4B" }), _jsx("p", { className: "mt-1 text-xs text-zinc-600", children: "Your feedback means a lot." })] })) })] }));
}
