import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Menu, Moon, Sun } from "lucide-react";
import { useTheme } from "@/context/use-theme";
import { motion } from "framer-motion";
export function Navbar() {
    const { theme, toggleTheme } = useTheme();
    return (_jsx("header", { className: "fixed inset-x-0 top-6 z-50 px-4", children: _jsx("div", { className: "mx-auto max-w-6xl rounded-2xl border border-black/10 dark:border-white/10 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl shadow-lg", children: _jsxs("div", { className: "flex h-14 items-center justify-between px-6", children: [_jsxs("div", { className: "flex items-center gap-3 cursor-pointer", children: [_jsx("span", { className: "text-sm font-semibold tracking-wide text-zinc-900 dark:text-white", children: "Amal Thomas" }), _jsx("span", { className: "h-1.5 w-1.5 rounded-full bg-indigo-500" }), _jsx("span", { className: "text-xs font-medium text-zinc-500 dark:text-zinc-400", children: "MERN Stack" })] }), _jsxs("nav", { className: "hidden md:flex items-center gap-8 text-sm font-medium", children: [_jsx("a", { href: "#projects", className: "text-zinc-700 dark:text-zinc-300 hover:text-black dark:hover:text-white transition", children: "Projects" }), _jsx("a", { href: "#skills", className: "text-zinc-700 dark:text-zinc-300 hover:text-black dark:hover:text-white transition", children: "Skills" }), _jsx("a", { href: "#contact", className: "text-zinc-700 dark:text-zinc-300 hover:text-black dark:hover:text-white transition", children: "Contact" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: toggleTheme, className: "flex h-9 w-9 items-center justify-center rounded-xl transition hover:bg-zinc-100 dark:hover:bg-zinc-800", children: theme === "light" ? (_jsx(motion.div, { initial: { rotate: -90, opacity: 0 }, animate: { rotate: 0, opacity: 1 }, transition: { duration: 0.2 }, children: _jsx(Moon, { className: "size-5 text-zinc-700" }) }, "moon")) : (_jsx(motion.div, { initial: { rotate: -90, opacity: 0 }, animate: { rotate: 0, opacity: 1 }, transition: { duration: 0.2 }, children: _jsx(Sun, { className: "size-5 text-yellow-400" }) }, "sun")) }), _jsxs(Sheet, { children: [_jsx(SheetTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: "ghost", className: "md:hidden rounded-xl", children: _jsx(Menu, { className: "size-5" }) }) }), _jsx(SheetContent, { side: "right", className: "dark:bg-zinc-900", children: _jsxs("nav", { className: "mt-10 flex flex-col gap-6 text-lg font-medium", children: [_jsx("a", { href: "#projects", children: "Projects" }), _jsx("a", { href: "#skills", children: "Skills" }), _jsx("a", { href: "#contact", children: "Contact" })] }) })] })] })] }) }) }));
}
